Varrah buffer
waliot/rxjs-ru pull request #26
Opened 2020-10-18 21:49 UTC by Varrah

Added buffer.md

2020-10-19 18:19 UTC, mephistorine requested changes
Исправить все замечания! Хорошая работа!

2020-10-19 18:19 UTC, mephistorine commented on api/operators/creation/buffer.md
> + в этот момент метод выдает сигнал на выходной Observable и открывает новый внутренний буфер в ожидании следующего срабатывания closingNotifier.
```suggestion
Собирает элементы внутреннего потока в массив, пока внешний поток `closingNotifier` не отправит новое значение, как только это происходит внутренний поток отправляет в качестве значения массив всех буферезированных значений.
```

2020-10-19 18:19 UTC, mephistorine commented on api/operators/creation/buffer.md
> +OperatorFunction<T, T[]>: объект Observable содержащий буферы, которые являются массивами значений
Секцию "Возвращаемое значение удалить"

2020-10-19 18:19 UTC, mephistorine commented on api/operators/creation/buffer.md
> +- [window](api/operators/pipeable/window.md)
Удалить все ссылки на другие операторы. Оставить только две ссылки на офф. документацию и исходный код

2020-10-19 18:19 UTC, mephistorine commented on api/operators/creation/buffer.md
> +### Пример 1: на каждый клик выдавать массив с последними внутренними событиями
```suggestion
### Пример 1

На каждый клик поток `buffered` отправляет массив значений собранный из потока `intervalEvents`
```

2020-10-20 15:27 UTC, Varrah commented
> Исправить все замечания! Хорошая работа!

Исправил
Если теперь все хорошо, то теперь смогу быстрее перевести еще несколько статей в рамках отдельных PR

2020-10-20 15:36 UTC, mephistorine approved these changes

2020-10-20 15:39 UTC, mephistorine commented
@Varrah Перемести файл buffer.md в директорию `/api/operators/pipeable`. Тут есть некоторые тонкости того какого типа определенный оператор.

2020-10-20 15:40 UTC, mephistorine commented
@Varrah Здорово, создай задачу (пример #17) на оператор который ты хочешь перевести и по нему PR, в самой задаче спроси куда определить файл с переводом

2020-10-20 15:41 UTC, mephistorine requested changes
Еще немного)

2020-10-20 16:13 UTC, binakot approved these changes

2020-10-20 16:17 UTC, Varrah commented
> @Varrah Перемести файл buffer.md в директорию `/api/operators/pipeable`. Тут есть некоторые тонкости того какого типа определенный оператор.

fixed

2020-10-20 16:21 UTC, mephistorine approved these changes

2020-10-20 16:21 UTC, merged