Varrah audit
waliot/rxjs-ru pull request #29
Opened 2020-10-25 17:06 UTC by Varrah

Fixes #28

2020-10-25 17:56 UTC, binakot commented on api/operators/pipeable/audit.md
> +## Описание
Не хватает пустой строки между заголовком и текстом

2020-10-25 17:57 UTC, binakot commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует исходные значения для длительности определяемые другим объектом потока, затем выдает самое последние значен
```самое последние значение``` это что машинные перевод? 😄 Честно говоря, все предложение звучит как бред! @mephistorine поможешь?

2020-10-25 17:58 UTC, binakot commented on api/operators/pipeable/audit.md
> +Audit похож на throttle, но выдает последнеезначение полученное за время периода без оповещений, вместо первого из этих значений. Audit выдает последнее значение исходного потока на выходной объект п
```последнеезначение```, думаю, стоит проверять PR перед его созданием 😃

2020-10-25 20:00 UTC, Varrah commented on api/operators/pipeable/audit.md
> +## Описание
Исправил

2020-10-25 20:01 UTC, Varrah commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует исходные значения для длительности определяемые другим объектом потока, затем выдает самое последние значен
Исходное описание для меня местами тоже не слишком понятно, что и видно в переводе. Извините. Поспал, посмотрел свежим взглядом, поправил. Теперь лучше?

2020-10-25 20:02 UTC, Varrah commented on api/operators/pipeable/audit.md
> +Audit похож на throttle, но выдает последнеезначение полученное за время периода без оповещений, вместо первого из этих значений. Audit выдает последнее значение исходного потока на выходной объект п
Случается... Хорошо, что есть код ревью. Исправил.

2020-10-26 07:32 UTC, binakot commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует взодящие значения на время определяемое другим объектом потока, затем выдает последние значение из исходног
взодящие

2020-10-26 07:33 UTC, binakot commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует взодящие значения на время определяемое другим объектом потока, затем выдает последние значение из исходног
последние значение

2020-10-26 12:04 UTC, Varrah commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует взодящие значения на время определяемое другим объектом потока, затем выдает последние значение из исходног
Исправил

2020-10-26 15:07 UTC, mephistorine requested changes

2020-10-26 15:07 UTC, mephistorine commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует входящие значения на время определяемое другим объектом потока, затем выдает последнее значение из исходног
```suggestion
Игнорирует значения внутреннего потока, пока внешний поток не отправит не отправит значение, как только это происходит, отправляется последнее значение из внутреннего потока.
```

2020-10-26 15:07 UTC, mephistorine commented on api/operators/pipeable/audit.md
> +| `durationSelector` | Функция, которая получает значение из Observable-источника для расчета времени без оповещений, которое возвращается через Observable или Promise. |
```suggestion
| `durationSelector` | Функция, которая возвращает внешний поток за которым будет следить оператор `audit` |
```

2020-10-26 15:07 UTC, mephistorine commented on api/operators/pipeable/audit.md
> +### Пример 1: Выдавать клики с частотой не более одного в секунду
```suggestion
### Пример 1

Выдает событие клика с частотой, не более одного в секунду
```

2020-10-26 15:07 UTC, mephistorine commented on api/operators/pipeable/audit.md
> +- 📁 Исходный код: https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/OPERATOR_NAME.ts
Забыл добавить ссылки на исходники и на офф документацию

```suggestion
- 📰 Официальная документация: [audit](https://rxjs.dev/api/operators/audit)
- 📁 Исходный код: https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/audit.ts
```

2020-10-26 17:27 UTC, Varrah commented on api/operators/pipeable/audit.md
> +Похож на auditTime, но время без оповещений определяется вторым объектом потока. Игнорирует входящие значения на время определяемое другим объектом потока, затем выдает последнее значение из исходног
Исправил

2020-10-26 17:27 UTC, Varrah commented on api/operators/pipeable/audit.md
> +### Пример 1: Выдавать клики с частотой не более одного в секунду
Исправил

2020-10-26 18:20 UTC, binakot approved these changes

2020-10-26 18:22 UTC, binakot approved these changes

2020-10-26 18:33 UTC, mephistorine approved these changes

2020-10-26 18:33 UTC, merged